services:
  jupyterlab:
    image: jupyterdocker
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./:/contrans2025
    networks:
      - dbnetwork

  postgres:
    image: postgres

    #Qustion 1: what environment variables are required for this image?
    env_file:
      - .env
      
    #Question 2: Does this software have a port (inside the container) it runs on by default?
    ports:
      - "5432:5432"

    #Question 3: What folder inside the container stores the data you need to save?
    volumes:   
      - postgresdata:/var/lib/postgresql/18/docker 

    networks:
      - dbnetwork
  mysql:
    image: mysql

    #Qustion 1: what environment variables are required for this image?
    env_file:
      - .env
    #Question 2: Does this software have a port (inside the container) it runs on by default?
    ports:
      - "3306:3306"
    #Question 3: What folder inside the container stores the data you need to save?
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - dbnetwork

  mongo:
    image: mongo
    #Qustion 1: what environment variables are required for this image?
    env_file:
      - .env
    #Question 2: Does this software have a port (inside the container) it runs on by default?
    ports:
      - "27017:27017"
    #Question 3: What folder inside the container stores the data you need to save?
    volumes:
      - mongodata:/data/db
    networks:
      - dbnetwork

volumes:
  postgresdata:
  mysqldata:
  mongodata:

networks:
  dbnetwork: 